blank_issues_enabled: false
contact_links:
  - name: Feature Request & Questions
    url: https://discord.gg/mfU3TgfyWg
    about: Send suggestions or ask questions here instead of the issue tracker.
