name: Gradle (Pull Request)

on: [ pull_request ]

jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Android SDK build tools
        run: echo "${ANDROID_HOME}/build-tools/30.0.3" >> $GITHUB_PATH

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Build with PR changes
        run: |
          chmod +x gradlew
          ./gradlew deploy
