name: Gradle (Push)

on: [ push ]

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Build mind-util
        run: |
          chmod +x gradlew
          ./gradlew deploy

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mind-util
          path: build/libs/*.jar
